### ISSUE TITLE
同学你好，想请教一下部署hexo+语雀+github action的具体操作

### ISSUE THREAD

**Issue by hacker-jerry** [ResonateWithMe/blog#2]
同学你好，我也使用语雀同步github page，但是在push之后触发的github action只生成了一部分文件
![image](https://user-images.githubusercontent.com/57279550/91201183-b89e8900-e732-11ea-921e-b4442239cbcf.png)
而index.html文件中是空白，而且没有像你那些js css静态文件夹，请问你知道是哪里出了问题吗？或者你在部署的时候参考的是那些教程呢？期待你的帮助，感谢！

**Comment by ResonateWithMe** [comment]
很抱歉回复晚了。

**Comment by ResonateWithMe** [comment]
很抱歉我无法准确的给你教程，我也是网上查的，忘了看的哪篇了...
可能的问题：
1. 你在本地可以build成功吗？
2. 如果可以，那可能是action写错了，可以参考一下我的：https://github.com/ResonateWithMe/blog/blob/master/.github/workflows/main.yml

**Comment by hacker-jerry** [comment]
> 很抱歉我无法准确的给你教程，我也是网上查的，忘了看的哪篇了...
> 可能的问题：
> 
> 1. 你在本地可以build成功吗？
> 2. 如果可以，那可能是action写错了，可以参考一下我的：https://github.com/ResonateWithMe/blog/blob/master/.github/workflows/main.yml

没事啦，我已经解决了
